# Generated by Django 5.1.7 on 2025-03-15 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HeartDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("cp", models.IntegerField()),
                ("trestbps", models.IntegerField()),
                ("chol", models.IntegerField()),
                ("fbs", models.BooleanField()),
                ("restecg", models.IntegerField()),
                ("thalach", models.IntegerField()),
                ("exang", models.BooleanField()),
                ("oldpeak", models.FloatField()),
                ("slope", models.IntegerField()),
                ("ca", models.IntegerField()),
                ("thal", models.IntegerField()),
                ("prediction_result", models.CharField(max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heart_disease",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parkinson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("mdvp_fo_hz", models.FloatField()),
                ("mdvp_fhi_hz", models.FloatField()),
                ("mdvp_flo_hz", models.FloatField()),
                ("mdvp_jitter_percentage", models.FloatField()),
                ("mdvp_jitter_abs", models.FloatField()),
                ("mdvp_rap", models.FloatField()),
                ("mdvp_ppq", models.FloatField()),
                ("jitter_ddp", models.FloatField()),
                ("mdvp_shimmer", models.FloatField()),
                ("mdvp_shimmer_db", models.FloatField()),
                ("shimmer_apq3", models.FloatField()),
                ("shimmer_apq5", models.FloatField()),
                ("mdvp_apq", models.FloatField()),
                ("shimmer_dda", models.FloatField()),
                ("nhr", models.FloatField()),
                ("hnr", models.FloatField()),
                ("rpde", models.FloatField()),
                ("dfa", models.FloatField()),
                ("spread1", models.FloatField()),
                ("spread2", models.FloatField()),
                ("d2", models.FloatField()),
                ("ppe", models.FloatField()),
                ("prediction_result", models.CharField(max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parkinson",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
